apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gseo142bx-nodejs
  janus-idp.io/tekton: gseo142bx-nodejs
  backstage.io/kubernetes-id: gseo142bx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gseo142bx-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
